### ISSUE TITLE
Метрополитен1 

### ISSUE THREAD

**Issue by Dathator** [Dathator/academDz#1]
@vdetstvepil

**Comment by vdetstvepil** [comment]
**Файл Metro.cs**
- 9 строчка. Правильнее будет перенести инициализацию переменной в конструктор. Т.е. объявить ее там, где ты ее объявил, а строчку new перенести в конструктор. В остальных файлах то же самое.

**Файл Station.cs**
- 25 строка. Если присвоишь один список другому, то элементы из второго списка не перепрыгнут в первый. Знаком равно ты просто присваиваешь первому списку ссылку на второй список. Если у тебя второй список поменяется, удалится и т.п., изменения в первом списке проявятся немедленно. Как избежать: просто через цикл foreach добавить элементы из второго списка в основной список. Или воспользоваться функцией AddRange.

**Comment by vdetstvepil** [comment]
Молодец 👍 только поправь косяки и зачту
